### ISSUE TITLE
Cannot set flutter sdk to hidden directory

### ISSUE THREAD

**Issue by kodeaqua** [fahminlb33/KFlearning#6]
So i was installing flutter sdk to :
C:\Users\Aqua\.flutter

The installation was successful.

But after i opened Visual Studio Code and then run 'Flutter doctor' from Command Pallete, it showing error :
Could not find a Flutter SDK. Please ensure flutter is installed and in your PATH (you may need to restart).

You can check the log file from here:
https://del.dog/mifivexupp

The path is in right way :
[00:17:44] [General] [Info] Searching for SDKs...
[00:17:44] [General] [Info] Environment PATH:
[00:17:44] [General] [Info]     C:\Program Files\Common Files\Oracle\Java\javapath
[00:17:44] [General] [Info]     C:\Windows\system32
[00:17:44] [General] [Info]     C:\Windows
[00:17:44] [General] [Info]     C:\Windows\System32\Wbem
[00:17:44] [General] [Info]     C:\Windows\System32\WindowsPowerShell\v1.0\
[00:17:44] [General] [Info]     C:\Program Files\Microsoft VS Code\bin
[00:17:44] [General] [Info]     C:\Users\Aqua\AppData\Local\Microsoft\WindowsApps
[00:17:44] [General] [Info]     C:\Program Files (x86)\KF-MinGW\bin
[00:17:44] [General] [Info]     C:\Users\Aqua\.flutter\bin

Then i browsing the C:\Users\Aqua\, and found a directory named 'flutter' (not ".flutter")

The ".flutter" directory is empty

So the flutter sdk files are stored in "flutter" directory instead of ".flutter" directory

![image](https://user-images.githubusercontent.com/33061778/110358874-69d19480-806f-11eb-98d2-7ebd82d2d182.png)
![image](https://user-images.githubusercontent.com/33061778/110358908-73f39300-806f-11eb-8a1f-fdd2d319c055.png)
![image](https://user-images.githubusercontent.com/33061778/110358950-7bb33780-806f-11eb-9647-a4eccbecd59b.png)

Edit:
The installation path is
C : \ Users \ Aqua \ .flutter

not

C : \ Users \ Aqua . flutter

Idk why github filtered \ and . 🤣

**Comment by kodeaqua** [comment]
Deleting ".flutter" directory and then renaming "flutter" directory to ".flutter" will fixed the Visual Studio Code error

**Comment by fahminlb33** [comment]
Thank you for your report!

In Windows and UNIX system . means current directory and .. means one level directory above. When you install it on `.flutter`, Windows treat that name as extension, not folder, that's why the installation directory is wrongly placed in your user directory. Current solution is to not place a dot in front of your path and this problem is not really an issue since most of KFlearning user don't even use the custom install directory, hence this problem will not be resolved in upcoming release.

NB: GitHub filtered \\ because it's an escape character for Markdown, you have to use double backslash or use code block to prevent Markdown compiler to change your formatting.

**Comment by fahminlb33** [comment]
Because this issue doesn't have high impact to KFlearning functionality, thus this issue is marked as `wontfix` and will not be included as priority for the next release.
